version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  node:
    build:
      context: ./node
    image: sempredrf/fullcycle-node:latest
    container_name: node
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    image: sempredrf/fullcycle-nginx:latest
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - node

networks:
  node-network:
    driver: bridge