##
## Build
##
FROM golang:1.17-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download

COPY *.go ./

RUN go build -o /fullcycle-go

##
## Deploy
##

FROM scratch

WORKDIR /

COPY --from=builder /fullcycle-go /fullcycle-go

ENTRYPOINT ["/fullcycle-go"]